Month 8/step 2
theverybusybee/react-burger pull request #4
Opened 2022-09-15 21:56 UTC by theverybusybee

2022-09-15 23:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы! Очень Хорошая работа, почти нет никаких замечаний** 🔥

### **Но все же есть несколько, которые нужно исправить:**

- Расширение файлов где используется JSX-разметка, должно быть .jsx, за исключением входного файла index.js. Так мы даём понять, что там хранятся не просто функции,а JSX-разметка;

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

### **Сделает код лучше:**

- не нужно хранить отдельно в сторе массив ингредиентов для отправки, создавайте массив при отправке из данных конструктора. Вообще любое дублирование информации с сторе считается плохой практикой

- Во многих компонентах дублируется описание PropTypes ингредиента
  Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингредиента, а не дублировать

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/). 

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации,которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders


**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-15 23:26 UTC, ArslanMustafin commented on src/components/app/app.js
>      );
**Можно лучше:** Лучше вынести в отдельный компонент то что находится в if (только сам loader). И написать что-то такое.

```js 
 return (
 <div className={AppStyle.main}>
    <AppHeader />
    {isLoading ? (
      <Loader />
    ) : (
      <DndProvider backend={HTML5Backend}>
        <BurgerIngredients />
        <BurgerConstructor />
      </DndProvider>
    )}
  </div>
);
```

Также для пользователей будет лучше, если вы добавить еще и компонент ошибки. в таком случае конструкция немного измениться.

```js
return (
  <div className={AppStyle.main}>
    <AppHeader />
    {hasError && <Error />}
    {isLoading && <Loader />}
    {!hasError && !isLoading && (
      <DndProvider backend={HTML5Backend}>
        <BurgerIngredients />
        <BurgerConstructor />
      </DndProvider>
    )}
  </div>
);
```

2022-09-15 23:26 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +  );
**Можно лучше:** Тут можно сразу достать и buns и totalprice и т.д, с помощью деструктуризации - 
https://learn.javascript.ru/destructuring-assignment.

2022-09-15 23:26 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +  const [items, setItems] = useState(constructorElements);
**Надо исправить:** items и constructorElements, полностью повторяют друг друга, во всех действиях, так почему бы не использовать только constructorElements. Я могу быть не прав, поэтому в таком случае отпишите пожалуйста, под этим комментарием.

2022-09-15 23:26 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +    }
**Можно лучше:** Можно упросить применив к type тернарный оператор. 
``` js 
     type: ... ? SET_TOTAL_PRICE : RESET_TOTAL_PRICE,
```
Подробнее про него: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator.

2022-09-15 23:26 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.js
> +  useMemo(() => {
**Надо исправить:** Лучше для выполнения каких действий, который не требуют результат, использовать useEffect. 
useeffect - https://ru.reactjs.org/docs/hooks-reference.html#useeffect
usememo - https://ru.reactjs.org/docs/hooks-reference.html#usememo

2022-09-15 23:26 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.js
> +    getDistanceBetweenPoints(sauceRef.current, viewportCoords)
**Можно лучше:** Такие большие условия лучше вынести в отдельные переменные, либо вынести значения в отдельные переменные.

2022-09-15 23:26 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.js
> +  function changeTab() {
**Надо исправить:** changeTab следует занести в useEffect, так функция не будет создаваться заново каждый ререндер. 

А также в зависимостях useEffect можно указать dispatch, но это не обязательно, т.к react гарантирует что dispatch меняться не будет. Подробнее про warning линтера напишу в общем комментарии к работе.

2022-09-15 23:26 UTC, ArslanDev666 commented on src/components/constructor-elements/constructor-elements.js
>      return (
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-15 23:26 UTC, ArslanDev666 commented on src/components/constructor-elements/constructor-elements.js
> +  const y = useMotionValue(0);
**Можно лучше:** Было бы круто, пояснить комментарием, что эта переменная делает.

2022-09-15 23:26 UTC, ArslanDev666 commented on src/services/actions/actions.js
>  /* api reducer */
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2022-09-15 23:26 UTC, ArslanDev666 commented on src/services/reducers/drop-container-reducer.js
> +      };
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет пересчитываться в момент изменения бургера

2022-09-16 23:23 UTC, theverybusybee commented on src/components/burger-constructor/burger-constructor.js
> +  const [items, setItems] = useState(constructorElements);
Я использую тут стейт с items, ибо он нужен для библиотеки 'framer-motion', при помощи которой, я реализовывала перетаскивание ингредиентов внутри конструктора

2022-09-17 04:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +  const [items, setItems] = useState(constructorElements);
Окей) В таком случае, лучше дать коду маленький комментарий, чтобы в будущем у других ревьюеров не возникло вопросов, по этому поводу. Но видел вы уже дали, поэтому считаю вопрос исчерпан.

2022-09-17 04:58 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания были исправлены!🔥

**Работа была не простая, но вы справились. Вы молодцы!**

** Сделает код лучше:**

- Лучше также указать расширения файла `.jsx` у файлов: `modal, modal-overlay, order-details, tabs` ;

- В компоненте modal у вас есть условие: 
```js 
if (isOpened) {
    document.addEventListener("keydown", handleEscClose);
    return () => {
      document.removeEventListener("keydown", handleEscClose);
    };
}
``` 
Условие там не требуется, т.к при ремонтировке компонента, по умолчанию будет срабатывать очистка эффекта. 
https://ru.reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

2022-09-22 20:46 UTC, merged